//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public Consulta()
        {
            this.Prescripcions = new HashSet<Prescripcion>();
        }
    
        public int CodigoConsulta { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public System.TimeSpan HoraConsulta { get; set; }
        public int CodigoPaciente { get; set; }
        public int CodigoMedico { get; set; }
        public int CodigoUsuario { get; set; }
        public Nullable<int> RitmoCardiaco { get; set; }
        public Nullable<int> NivelAzucar { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> PresionArterial { get; set; }
        public Nullable<int> Estatura { get; set; }
        public bool Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Prescripcion> Prescripcions { get; set; }
    }
}
