//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlMedicoEntities : DbContext
    {
        public ControlMedicoEntities()
            : base("name=ControlMedicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consulta> Consultas { get; set; }
        public virtual DbSet<Dia> Dias { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<Ingreso> Ingresoes { get; set; }
        public virtual DbSet<IngresoDetalle> IngresoDetalles { get; set; }
        public virtual DbSet<Medicamento> Medicamentoes { get; set; }
        public virtual DbSet<MedicamentoPresentacion> MedicamentoPresentacions { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
        public virtual DbSet<MedicoHorario> MedicoHorarios { get; set; }
        public virtual DbSet<MedicoHorarioRegular> MedicoHorarioRegulars { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Prescripcion> Prescripcions { get; set; }
        public virtual DbSet<PrescripcionMedicamento> PrescripcionMedicamentos { get; set; }
        public virtual DbSet<PrescripcionSintoma> PrescripcionSintomas { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<ProveedorMedicamento> ProveedorMedicamentoes { get; set; }
        public virtual DbSet<Sintoma> Sintomas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoSangre> TipoSangres { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedidas { get; set; }
        public virtual DbSet<UnidadTiempo> UnidadTiempoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
