//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia
    {
        public Dia()
        {
            this.MedicoHorarioRegulars = new HashSet<MedicoHorarioRegular>();
        }
    
        public int CodigoDia { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<MedicoHorarioRegular> MedicoHorarioRegulars { get; set; }
    }
}
