//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoDetalle
    {
        public int IngresoDetalleCodigo { get; set; }
        public int IngresoCodigo { get; set; }
        public int CodigoMedicamento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ValorUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Ingreso Ingreso { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
