//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public Ingreso()
        {
            this.IngresoDetalles = new HashSet<IngresoDetalle>();
        }
    
        public int IngresoCodigo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> NumeroReferencia { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
        public Nullable<int> SerieFactura { get; set; }
        public Nullable<int> CodigoProveedor { get; set; }
        public int CodigoUsuario { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<IngresoDetalle> IngresoDetalles { get; set; }
    }
}
