//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoHorario
    {
        public int MedicoHorario1 { get; set; }
        public Nullable<int> CodigoMedico { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
    
        public virtual Medico Medico { get; set; }
    }
}
