//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentoPresentacion
    {
        public MedicamentoPresentacion()
        {
            this.Medicamentoes = new HashSet<Medicamento>();
        }
    
        public int CodigoMedicoPresentacion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Medicamento> Medicamentoes { get; set; }
    }
}
