//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public Medicamento()
        {
            this.IngresoDetalles = new HashSet<IngresoDetalle>();
            this.PrescripcionMedicamentos = new HashSet<PrescripcionMedicamento>();
            this.ProveedorMedicamentoes = new HashSet<ProveedorMedicamento>();
        }
    
        public int CodigoMedicamento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Especificaciones { get; set; }
        public int CodigoMedicamentoPresentacion { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> MargenGanancia { get; set; }
    
        public virtual ICollection<IngresoDetalle> IngresoDetalles { get; set; }
        public virtual MedicamentoPresentacion MedicamentoPresentacion { get; set; }
        public virtual ICollection<PrescripcionMedicamento> PrescripcionMedicamentos { get; set; }
        public virtual ICollection<ProveedorMedicamento> ProveedorMedicamentoes { get; set; }
    }
}
