//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public Medico()
        {
            this.Consultas = new HashSet<Consulta>();
            this.MedicoHorarios = new HashSet<MedicoHorario>();
            this.MedicoHorarioRegulars = new HashSet<MedicoHorarioRegular>();
        }
    
        public int CodigoMedico { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
    
        public virtual ICollection<Consulta> Consultas { get; set; }
        public virtual ICollection<MedicoHorario> MedicoHorarios { get; set; }
        public virtual ICollection<MedicoHorarioRegular> MedicoHorarioRegulars { get; set; }
    }
}
