//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion
    {
        public Prescripcion()
        {
            this.PrescripcionMedicamentos = new HashSet<PrescripcionMedicamento>();
            this.PrescripcionSintomas = new HashSet<PrescripcionSintoma>();
        }
    
        public int CodigoPrescripcion { get; set; }
        public int CodigoConsulta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CodigoUsuario { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual ICollection<PrescripcionMedicamento> PrescripcionMedicamentos { get; set; }
        public virtual ICollection<PrescripcionSintoma> PrescripcionSintomas { get; set; }
    }
}
