//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescripcionSintoma
    {
        public int CodigoPrescripcionSintomas { get; set; }
        public int CodigoPrescripcion { get; set; }
        public int CodigoSintoma { get; set; }
    
        public virtual Prescripcion Prescripcion { get; set; }
        public virtual Sintoma Sintoma { get; set; }
    }
}
