//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescripcionMedicamento
    {
        public int CodigoPrescripcionMedicamentos { get; set; }
        public int CodigoPrescripcion { get; set; }
        public int Cantidad { get; set; }
        public int CodigoMedicamento { get; set; }
        public Nullable<int> CodigoUnidadTiempo { get; set; }
        public Nullable<decimal> Dosis { get; set; }
        public Nullable<int> CodigoUnidadMedida { get; set; }
        public Nullable<decimal> Dosificacion { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Prescripcion Prescripcion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
