//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorMedicamento
    {
        public int ProveedorMedicamento1 { get; set; }
        public int CodigoProveedor { get; set; }
        public int CodigoMedicamento { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
