//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Ingresoes = new HashSet<Ingreso>();
            this.ProveedorMedicamentoes = new HashSet<ProveedorMedicamento>();
        }
    
        public int CodigoProveedor { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<Ingreso> Ingresoes { get; set; }
        public virtual ICollection<ProveedorMedicamento> ProveedorMedicamentoes { get; set; }
    }
}
