//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sintoma
    {
        public Sintoma()
        {
            this.PrescripcionSintomas = new HashSet<PrescripcionSintoma>();
        }
    
        public int CodigoSintoma { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Especificaciones { get; set; }
    
        public virtual ICollection<PrescripcionSintoma> PrescripcionSintomas { get; set; }
    }
}
