//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Consultas = new HashSet<Consulta>();
            this.Ingresoes = new HashSet<Ingreso>();
        }
    
        public int CodigoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Password { get; set; }
        public int CodigoTipoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaSesion { get; set; }
    
        public virtual ICollection<Consulta> Consultas { get; set; }
        public virtual ICollection<Ingreso> Ingresoes { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
